# Site settings
title: Coding Love <3
header-img: img/home-bg.jpg
email: christophmartin@gmx.at
copyright_name: Your/Project/Corporate Name
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://yourdomain.com"
# twitter_username: SBootstrap
github_username:  cmaart
# facebook_username:  StartBootstrap
email_username:  christophmartin@gmx.at
amazon_associate_id: cmart_blog-21

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: "UA-94002359-1"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
